[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "atm-controller"
version = "0.1.0"
description = "An ATM Controller system implementation"
readme = "README.md"
requires-python = ">=3.11"
